#!/bin/bash

for f in examples/*.elm; do
  ./scripts/build-example "$(basename "$f")" --optimize
done

for f in public/[[:upper:]]*.js; do
  echo "Uglifying $f"
  uglifyjs "$f" --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output="$f"
done
